name: Bug report
description: Report a problem in Homicide Detective
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Be as specific as possible
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, Browser (for web), Python/PyQt versions (for desktop)
